#version 450
layout (local_size_x = 8, local_size_y = 8, local_size_z = 1) in;
layout (set = 0, binding = 1, rgba8) readonly uniform image2D sceneColorBuffer;
layout (set = 1, binding = 0, rgba8) writeonly uniform image2D tempSurface;
layout (set = 1, binding = 1, rgba8) readonly uniform image2D modelColorBuffer;

void main() {

    ivec2 screen_pos = ivec2(gl_GlobalInvocationID.xy);
    ivec2 screen_size = imageSize(sceneColorBuffer);

    if (screen_pos.x < 0 || screen_pos.x >= screen_size.x || screen_pos.y < 0 || screen_pos.y >= screen_size.y) {
        return;
    }

    vec4 modelColor = imageLoad(modelColorBuffer, screen_pos);
    vec4 sceneColor = imageLoad(sceneColorBuffer, screen_pos);
    vec4 color = mix(sceneColor, modelColor, modelColor.a);
    imageStore(tempSurface, screen_pos, color);
}
